#!/usr/bin/env python

from __future__ import print_function

import os

# os.system("root -b -q \"/home/tmudholk/research/hgcal_analysis/hgcal_optimization/analysis/macros/plotE_resolution_high_stats.C++(34,\\\"high_stats_version34\\\",\\\"/home/tmudholk/data/high_stats_version34\\\",\\\"/home/tmudholk/research/hgcal_analysis/hgcal_optimization/analysis/macros\\\")\"")
# os.system("root -b -q \"/home/tmudholk/research/hgcal_analysis/hgcal_optimization/analysis/macros/plotE_resolution_high_stats.C++(44,\\\"high_stats_vflat\\\",\\\"/home/tmudholk/data/high_stats_vflat\\\",\\\"/home/tmudholk/research/hgcal_analysis/hgcal_optimization/analysis/macros\\\")\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(33,\\\"version33\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_33/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",0.5)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(33,\\\"version33\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_33/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",2.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(33,\\\"version33\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_33/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30_old_raw\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/old_version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",0.5)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30_raw\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",0.5)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",20.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",50.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats_alt.C++(30,\\\"version30_alt\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats_alt.C++(30,\\\"version30_alt\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",20.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats_alt.C++(30,\\\"version30_alt\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",50.0)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0, 1)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",20.0, 1)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",50.0, 1)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30_raw\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0, 2)\"")

# os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30_raw\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",50.0, 2)\"")

os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",5.0, 1)\"")

os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",20.0, 1)\"")

os.system("root -b -q \"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros/plotE_resolution_high_stats.C++(30,\\\"version30\\\",\\\"/afs/cern.ch/user/t/tmudholk/private/mount/eos_mount/cms/store/user/tmudholk/hexagonal_geometry/version_30/githexaV02-01-01/gamma\\\",\\\"/afs/cern.ch/user/t/tmudholk/public/research/hgcal_optimization_latest/PFCal/PFCalEE/analysis/macros/optimization_macros\\\",50.0, 1)\"")
